sudo: required
dist: trusty
language: node_js
node_js:
- '6'
services:
- mongodb
addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

deploy:
- provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: brewerbucket
  key: latest.zip
  bundle_type: zip
  application: codebrewers
  deployment_group: master
  region: us-west-2





